# -- Notebook 00: Setup --

**Summary of the notebook:**

* Brief look at the structure of each individual dataset
* Merges the three different datasets from the Road Safety Dataset: Collisions, Vehicles, and Casualties

In [ ]:
# Necessary libraries: 

import pandas as pd 
from pathlib import Path

In [17]:
base_path = Path(r"C:/Users/abhik/OneDrive/Desktop/WISE")
    # This base path is local to my laptop; edit as required 
    # The base path is until the WISE folder 
collision_raw_path = base_path / "Data" / "Raw" / "dft-road-casualty-statistics-collision-last-5-years.csv"
vehicle_raw_path = base_path / "Data" / "Raw" / "dft-road-casualty-statistics-vehicle-last-5-years.csv"
casualty_raw_path = base_path / "Data" / "Raw" / "dft-road-casualty-statistics-casualty-last-5-years.csv"

In [18]:
print(casualty_raw_path)
print(collision_raw_path)
print(vehicle_raw_path)

C:\Users\abhik\OneDrive\Desktop\WISE\Data\Raw\dft-road-casualty-statistics-casualty-last-5-years.csv
C:\Users\abhik\OneDrive\Desktop\WISE\Data\Raw\dft-road-casualty-statistics-collision-last-5-years.csv
C:\Users\abhik\OneDrive\Desktop\WISE\Data\Raw\dft-road-casualty-statistics-vehicle-last-5-years.csv

In [19]:
# This creates a dataframe for each of the downloaded files 

casualty_df = pd.read_csv(casualty_raw_path)
collision_df = pd.read_csv(collision_raw_path)
vehicle_df = pd.read_csv(vehicle_raw_path)

C:\Users\abhik\AppData\Local\Temp\ipykernel_59448\4025927276.py:5: DtypeWarning: Columns (0: generic_make_model) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicle_df = pd.read_csv(vehicle_raw_path)

The warnings here indicate that the collision_df dataset has mixed types for the collision_index and collision_ref_no variables. The same applies to the generic_make_model variable in the vehicle_raw dataset. This is important to consider because it means that if we attempt merging the datasets together, observations with the same collision_index value may not be properly merged together because the values across different datasets are stored as different object types. Therefore, we should take the recommendation that has been given in the message above to force a data type option for those specific rows.

In [20]:
dtype_map = {'collision_index': str, 'collision_ref_no': str, 'collision_year': str, 'generic_make_model':str}

casualty_df = pd.read_csv(casualty_raw_path, dtype=dtype_map)
collision_df = pd.read_csv(collision_raw_path, dtype=dtype_map)
vehicle_df = pd.read_csv(vehicle_raw_path, dtype=dtype_map)

**Loading datasets:**

In [18]:
# Simple and brief check that the dataframe has been loaded correctly 

casualty_df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2021170H10421,2021,170H10421,447098.0,532997.0,-1.270905,54.689833,17,3,2,...,0,0,2,1,2,E01011959,-1,0,0.293588,0.706412
1,2021170H11231,2021,170H11231,450486.0,533118.0,-1.218333,54.690592,17,3,2,...,0,0,1,2,2,E01011973,-1,0,0.017448,0.982552
2,2020170M11750,2020,170M11750,449694.0,519733.0,-1.232884,54.570397,17,3,2,...,0,0,1,1,2,E01012092,-1,0,0.128730,0.871270
3,2021170M31761,2021,170M31761,449744.0,514217.0,-1.233040,54.520825,17,3,1,...,0,0,2,1,2,E01032553,-1,0,0.182698,0.817302
4,2021170S10441,2021,170S10441,445971.0,520834.0,-1.290292,54.580641,17,3,3,...,0,13,2,1,1,E01012258,-1,0,0.016094,0.983906

In [19]:
collision_df.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,0,0,0,3,E01003536,-1,0,0.0,1.0,-1
1,202031D109620,2020,31D109620,1,1,3,2,95,11,2,...,0,0,0,6,E01028156,-1,0,1.0,0.0,-1
2,2020401003715,2020,401003715,1,1,3,1,39,7,3,...,0,0,0,2,E01017492,3,1,0.0,1.0,-1
3,2021201086330,2021,201086330,1,1,3,1,63,9,3,...,0,2,0,3,E01009140,3,1,0.0,1.0,-1
4,2021371050963,2021,371050963,1,1,3,1,51,8,3,...,0,0,0,9,E01030190,3,1,0.0,1.0,-1

In [20]:
vehicle_df.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2020210979534,2020,210979534,2,5,0,3,3,4,6,...,57,9,798,1,4,BMW F 800,3,E01010422,0,-1
1,2020030959800,2020,030959800,1,5,0,17,19,2,6,...,59,9,798,1,3,BMW F 800,6,E01025351,0,-1
2,2020360978858,2020,360978858,2,5,0,18,19,8,4,...,64,9,798,1,11,BMW F 800,4,E01026874,0,-1
3,2020430340711,2020,430340711,1,5,0,18,19,3,7,...,48,8,798,1,8,BMW F 800,8,E01017758,0,-1
4,2020010260297,2020,010260297,1,5,0,99,99,9,9,...,36,7,798,1,9,BMW F 800,8,E01016121,0,-1

In [21]:
# This checks that the number of different collisions that the datasets have data on are the same
# This isn't required to be the same as only the rows with matching collision reference numbers will be the same, but it is useful to see if there are any discrepancies

print("Causalty dataset:", len(pd.unique(casualty_df['collision_ref_no'])))
print("Colliison dataset:" , len(pd.unique(collision_df['collision_ref_no'])))
print("Vehicle dataset:" , len(pd.unique(vehicle_df['collision_ref_no'])))

Causalty dataset: 501768
Colliison dataset: 501768
Vehicle dataset: 501768

In [22]:
# This checks the shape of each dataset:

print("Collision dataset", collision_df.shape)
print("Casualty dataset", casualty_df.shape)
print("Vehicle dataset", vehicle_df.shape)

# We see that there are more observations for each unique collision (which makes sense intuitively, e.g.: for each collision there will be at least two different vehicles)

Collision dataset (640522, 23)
Casualty dataset (503475, 44)
Vehicle dataset (920692, 32)

**Merging datasets:**

In [23]:
# Seeing which columns are common across all 3 datasets: 
print(set(collision_df.columns) & set(vehicle_df.columns) & set(casualty_df))

# Seeing which columns are common across collision_df and vehicle_df: 
print(set(collision_df.columns) & set(vehicle_df.columns))

# Seeing which columns are common across vehicle_df and causalty_df: 
print(set(vehicle_df.columns) & set(casualty_df))

# Seeing which columns are common across collision_df and causalty_df: 
print(set(collision_df.columns) & set(casualty_df))

{'collision_index', 'collision_ref_no', 'collision_year'}
{'collision_index', 'collision_year', 'vehicle_reference', 'collision_ref_no'}
{'collision_index', 'collision_year', 'collision_ref_no'}
{'collision_index', 'collision_year', 'collision_ref_no'}

In [24]:
# Merging the vehicle and collision datasets: 
collision_combined_1 = collision_df.merge(vehicle_df, on = ['collision_ref_no', 'collision_index', 'collision_year'])

In [25]:
collision_combined_1.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference_x,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,-1,-1,-1,-1,-1,-1,-1,-1,0,-1
1,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,-1,-1,-1,-1,-1,-1,-1,-1,0,-1
2,202031D109620,2020,31D109620,1,1,3,2,95,11,2,...,28,6,2996,1,1,LAND ROVER RANGE ROVER SPORT,1,E01013959,0,-1
3,2020401003715,2020,401003715,1,1,3,1,39,7,3,...,-1,-1,-1,-1,-1,-1,-1,-1,0,-1
4,2021201086330,2021,201086330,1,1,3,1,63,9,3,...,64,9,1200,1,1,PEUGEOT 2008,4,E01028587,0,-1

In [ ]:
print(collision_combined_1.shape)
# The combined dataset has 1,221,287 rows and 52 columns

(1221287, 52)

In [30]:
collision_combined_2 = collision_combined_1.merge(casualty_df, on = ['collision_ref_no', 'collision_index', 'collision_year'])

In [31]:
collision_combined_2.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference_x,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,0,0,1,3,2,E01003538,-1,0,0.0,1.0
1,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,0,0,1,3,2,E01003538,-1,0,0.0,1.0
2,202031D109620,2020,31D109620,1,1,3,2,95,11,2,...,0,0,1,1,2,E01028156,-1,0,1.0,0.0
3,2020401003715,2020,401003715,1,1,3,1,39,7,3,...,0,0,1,1,2,E01017466,3,1,0.0,1.0
4,2021201086330,2021,201086330,1,1,3,1,63,9,3,...,0,0,1,2,2,E01009200,3,1,0.0,1.0

In [ ]:
print(collision_combined_2.shape)
# The final combined dataset has 1,221,287 rows and 93 columns

(1221287, 93)

**Final dataset:**

In [33]:
collisions_00 = collision_combined_2
# Relabelling this for future convenience + clarity: this dataset now needs to be cleaned (see notebook 01)

In [34]:
collisions_00.head(25)

,collision_index,collision_year,collision_ref_no,vehicle_reference_x,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,0,0,1,3,2,E01003538,-1,0,0.000000,1.000000
1,2020010280094,2020,010280094,1,1,3,2,24,5,3,...,0,0,1,3,2,E01003538,-1,0,0.000000,1.000000
2,202031D109620,2020,31D109620,1,1,3,2,95,11,2,...,0,0,1,1,2,E01028156,-1,0,1.000000,0.000000
3,2020401003715,2020,401003715,1,1,3,1,39,7,3,...,0,0,1,1,2,E01017466,3,1,0.000000,1.000000
4,2021201086330,2021,201086330,1,1,3,1,63,9,3,...,0,0,1,2,2,E01009200,3,1,0.000000,1.000000
5,2021371050963,2021,371050963,1,1,3,1,51,8,3,...,0,0,1,3,2,E01030190,3,1,0.000000,1.000000
6,2022161255871,2022,161255871,1,1,3,2,60,9,3,...,0,0,1,1,2,E01033104,3,1,0.000000,1.000000
7,2023201345434,2023,201345434,1,1,3,1,72,10,3,...,0,0,1,1,2,E01009007,3,1,0.000000,1.000000
8,2024041434010,2024,041434010,1,1,3,1,39,7,2,...,-1,0,2,1,1,E01025105,5,1,1.000000,0.000000
9,2020140992628,2020,140992628,2,1,1,1,17,4,3,...,0,0,2,1,2,E01007596,3,1,0.000000,1.000000
10,2020140992628,2020,140992628,2,1,1,1,17,4,3,...,0,0,2,1,2,E01007596,3,1,0.000000,1.000000
11,202031D139820,2020,31D139820,2,1,1,1,11,3,3,...,0,0,1,2,2,E01028175,-1,0,0.069409,0.930591
12,202031D139820,2020,31D139820,2,1,1,1,11,3,3,...,0,0,1,2,2,E01028175,-1,0,0.069409,0.930591
13,2021361061716,2021,361061716,1,1,1,1,21,5,2,...,0,0,1,1,2,E01026597,7,1,1.000000,0.000000
14,2021361061716,2021,361061716,1,1,1,1,21,5,2,...,0,0,1,1,2,E01026597,7,1,1.000000,0.000000
15,2023522400767,2023,522400767,2,1,1,1,18,4,3,...,0,0,1,1,2,E01014489,-1,0,0.072491,0.927509
16,2023522400767,2023,522400767,2,1,1,1,18,4,3,...,0,0,1,1,2,E01014489,-1,0,0.072491,0.927509
17,2021010304813,2021,010304813,2,1,1,2,22,5,2,...,0,0,1,1,2,E01004581,-1,0,1.000000,0.000000
18,2021010304813,2021,010304813,2,1,1,2,22,5,2,...,0,0,1,1,2,E01004581,-1,0,1.000000,0.000000
19,2023010425559,2023,010425559,1,1,1,1,21,5,3,...,0,0,1,1,2,E01002022,-1,0,0.000000,1.000000
20,2023010425559,2023,010425559,1,1,1,1,21,5,3,...,0,0,1,1,2,E01002022,-1,0,0.000000,1.000000
21,2023010425559,2023,010425559,1,1,1,1,21,5,3,...,0,0,1,1,2,E01002022,-1,0,0.000000,1.000000
22,2024111476642,2024,111476642,1,1,1,1,25,5,2,...,-1,0,2,1,2,E01020765,7,1,1.000000,0.000000
23,202006A271023,2020,06A271023,2,2,1,1,35,6,3,...,0,0,1,1,2,E01005063,-1,0,0.164171,0.835829
24,202006A271023,2020,06A271023,2,2,1,1,35,6,3,...,0,0,1,1,2,E01005063,-1,0,0.164171,0.835829

In [ ]:
# Exporting this dataset [edit file path as necessary]: 

collisions_00.to_csv('C:/Users/abhik/OneDrive/Desktop/WISE/Data/Processed/collisions_00.csv', index = False)